apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmosapp
  labels:
    purpose: example-app-that-communicates-with-cosmosdb-msi
    app: cosmosapp
    aadpodidbinding: "cosmosdbappid"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmosapp
  template:
    metadata:
      labels:
        app: cosmosapp
    spec:
      containers:
        - name: cosmosapp
          image: mahinescluster.azurecr.io/cosmosapp
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: AZURE_CLIENT_ID
              value: "71ac8979-e82e-4ec6-819d-a1ed4a0e332a"